### ISSUE TITLE
Centering a graph chart

### ISSUE THREAD

**Issue by billmcknight1953** [xieziyu/ngx-echarts#219]
I have a chart showing a 'graph' type of chart, where the layout type is 'force'.   The chart displays in a div which can be toggled to a large size or back to its normal (smaller) size. Roam is set to true so that it can be moved and zoomed.  

If I drag the chart in the large canvas/div too far to the left, then when it the div is toggled back its smaller size, it cannot be seen.

The chart canvas does resize to the correct height and width, when toggled either direction, but the chart itself does not reappear in the smaller canvas if it has been manually dragged to the left in the larger canvas.

Is there a way to force the chart to redraw in the smaller canvas after it has been moved?

BTW, neither an explicit call to resize() nor setting [autoResize] made any difference

**Comment by sawyerbutton** [comment]
@billmcknight1953 
For the resize() function and [autoResize] @Input property,  In fact, there is no difference between them from functional perspective.
`[autoResize]` @input property willing to be triggered by window resize event & the ngDoCheck lifecycle hook, both processes will call `resize()` function in the end.
So in practice, if you want to control chart resize event manually, choose `resize()` function.
If manual operation is not your option, `[autoResize]` @Input property will help your chart auto-resize during every `ngDoCheck` lifecycle hook(pre-requirement:  @Input() properties change events existing).

**Comment by sawyerbutton** [comment]
> Is there a way to force the chart to redraw in the smaller canvas after it has been moved?

@billmcknight1953 ,  read this: [draggable force layout graph resize issue](https://github.com/apache/incubator-echarts/issues/9954#issue-412377455), currently, there is not an official solution provided.

From my perspective,  this issue could be fixed by recreating the graph totally.
Listening for window `resize` event, using `chart.dispose()` destroy the chart, then using existing `option` data recreating the force-layout graph again. BTW, recreating process will take up a huge amount of CPU-Resource, so taking `resize ` event callback function wisely.

**Comment by billmcknight1953** [comment]
My solution was to use an *ngIf condition to force a completely new rendering of the chart. There were two identical chart elements in the html, each with its own *ngIf condition.  This was possible because the chart json could be re-used.  It felt like a hack, but approximated the behavior I needed.
