### ISSUE TITLE
Why using ngDoCheck lifecycle hook to auto-resizing chart

### ISSUE THREAD

**Issue by sawyerbutton** [xieziyu/ngx-echarts#222]
```typescript
  ngDoCheck() {
    // No heavy work in DoCheck!
    if (this.chart && this.autoResize) {
      const offsetWidth = this.el.nativeElement.offsetWidth;
      const offsetHeight = this.el.nativeElement.offsetHeight;

      if (this.currentOffsetWidth !== offsetWidth || this.currentOffsetHeight !== offsetHeight) {
        this.currentOffsetWidth = offsetWidth;
        this.currentOffsetHeight = offsetHeight;
        this.resize();
      }
    }
  }
```

The only scenario I met is the chart's container size change. 
Using `ngDoCheck` Hook to check the chart's size status change is not a wise idea.

Using `ngOnChange` hook to do this is also workable. If we really need to listen to the size change of the chart's parent container, the developer should code it outside of `ngx-echarts`.

**Comment by xieziyu** [comment]
@sawyerbutton 
Yes, I can't agree more, my friend! I don't think using `ngDoCheck` is a wise idea too.
But I have to make a concession if I want `ngx-echarts` more easily to use. Especially when we want to use it within `<ng-template></ng-template>` just like some UI library such as `ng-zorro`.

Let's take a look at this simple code snippet:

```html
<nz-tabset>
  <nz-tab nzTitle="Tab 1">
    <div echarts [options]="option" [autoResize]="false"></div>
  </nz-tab>
  <nz-tab nzTitle="Tab 2">
    <div echarts [options]="option" [autoResize]="false"></div>
  </nz-tab>
  <nz-tab nzTitle="Tab 3">
    <div echarts [options]="option" [autoResize]="false"></div>
  </nz-tab>
</nz-tabset>
```

We disable the `autoResize` checking here. The charts in Tab 2 and Tab 3 can not show because they have zero width when initialized. So the developers have to work it out and write some unexpected codes.

What I have done here is to make sure the chart can *automatically* fit the container, without any additional codes involved. If the developers really want to handle the size change events manually, they still can set `[autoResize]` to `false` and work it out. It's an optional feature.

Thank you for your advise! I'm really appreciate any improvements that can achieve the same objective without using `ngDoCheck` life hook.

**Comment by sawyerbutton** [comment]
@xieziyu , Thanks for the patience.  
Truly, it's not comfortable for the developer adding more reactive-code for `size-change` event, I thought concession for `ng-template` scenario is unavoidable. `ngDoCheck` is Okay Here.
**But not every developer will face this issue**, as a wrapper-lib, my opinion, `ngx-echarts` should provide both noob and a manual way for the performance purpose.
Currently, `resize()` function is `private` function inside `ngx-echarts`, maybe we should realse it as public function. 

Considering below code (Not in `ng-template` scenario):
```typescript
// ngx-charts related code
public resize(chart?: EchartInstance) {
  this.chart.resize()
}
```

```typescript
// developer code
constructor(
  @Self private chartInstance: echarts,
  private zone: NgZone
) {}

reactiveLogicFunction() {
  // runOutsideAngular is optional
  this.zone.runOutsideAngular(() => {
     this.chartInstance.resize();
  })
}
```
If it is possible to provide more performance options for the developer, the world will be better.
