### ISSUE TITLE
怎么清除缓存？

### ISSUE THREAD

**Issue by wyl199** [xieziyu/ngx-echarts#30]

**Comment by xieziyu** [comment]
什么缓存？

**Comment by wyl199** [comment]
当你重新请求数据时两次请求数据会合并，在echarts中可以使用setOption(option, true)这个方法第二个参数设为true就可以清除之前的数据了， 但在ngx-echarts中该怎么操作？

**Comment by xieziyu** [comment]
@wyl199 直接变更dataset或者options对象的引用即可。demo中有例子

**Comment by ccm417** [comment]
xieziyu你好，使用了你在其它issue中提到的Object.assign方法，把options的值，以及引用都更新了，然后仍然出现了楼主所说的现象，两次数据合并在一组series中，即使现在legend都完全不同了。
请问是不是需要clear，另一个issue中提到的clear()用法是怎么使用的呢？能否示例一下，谢谢。

**Comment by ccm417** [comment]
另外，如果在多个legend,多个series的场景下，如何使用dataset来进行数据更新？感觉没有办法跟name匹配的嘛。谢谢

**Comment by edgexie** [comment]
@ccm417 @xieziyu
At first, thanks for your `directive`.
I got the same issue like landlord said.
It sames when controller's `chartOpt` witch bind to `options` change its `series` to more charts class, the charts not refresh. For example: One line dynamic update to two lines, the first one also stay there.
 
Because of this, I use `@ViewChild` like this:
* HTML
```html
<echarts-ng2 #echarts  [theme]="'macarons'"></echarts-ng2>
```
* ts
```
@ViewChild('echarts') echarts: ECharts;
// when i refresh the chart

// first
this.echarts.clear();
// then
this.echarts.setOption(newOpt)
```
I feel it's not the good idea.
Any idea?

**Comment by xieziyu** [comment]
在1.2.5中可以通过直接设置options为{}，来清除缓存。
所以我关闭这条issue啦
#42
